on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
    build:
      runs-on: ubuntu-latest
      timeout-minutes: 15
      steps:
        - uses: actions/checkout@v3
        - name: Verify commit exists in origin/main
          run: |
            git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
            git branch --remote --contains | grep origin/main
        - name: Set VERSION variable from tag
          run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        - name: "Setup Dotnet"
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.0.x
        - name: Restore Dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test --no-build
        - name: Pack
          run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
        - name: Push
          run: dotnet push FileRift.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${API_KEY}
          env:
            API_KEY: ${{secrets.NUGET_KEY}}

  
  